version: '3.8'
services:
  auth-service-db:
    image: mongo:6.0
    container_name: auth-service-db
    restart: unless-stopped
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_DATABASE: auth-service-db
      MONGO_INITDB_ROOT_USERNAME: useradmin
      MONGO_INITDB_ROOT_PASSWORD: userpassword
    volumes:
      - auth-service-db-data:/data/db
volumes:
  auth-service-db-data:
