version: '3.8'

services:
  auth-service:
    build: .
    container_name: auth-service-docker
    restart: unless-stopped
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - PORT=4000
      - HOST=0.0.0.0
      - MONGODB_URI=mongodb://mongo:27017/auth_service_dev
      - JWT_SECRET=auth_service_jwt_dev_secret_123
      - JWT_EXPIRES_IN=24h
      - BCRYPT_ROUNDS=10
      - LOG_LEVEL=debug
      - CORS_ORIGIN=http://localhost:3000,http://localhost:3010
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - auth-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  mongo:
    image: mongo:5.0
    container_name: auth-mongo-docker
    restart: unless-stopped
    ports:
      - '27018:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=authuser
      - MONGO_INITDB_ROOT_PASSWORD=auth_mongo_dev_123
      - MONGO_INITDB_DATABASE=auth_service_dev
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - auth-network

volumes:
  mongo_data:

networks:
  auth-network:
    driver: bridge
